### ISSUE TITLE
quarkus update removes comments from POM

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/quarkus-updates#129]
When I run `quarkus update`, if there are comments in my POM, e.g. like this:

```
  <properties>
    <compiler-plugin.version>3.12.1</compiler-plugin.version>
    <maven.compiler.release>17</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
    <quarkus.version>3.7.3</quarkus.version>
    <revision>999-SNAPSHOT</revision>
    <skipITs>true</skipITs>
    <surefire-plugin.version>3.2.5</surefire-plugin.version>
    <test.jvm.args>-Xms2g -Xmx2g</test.jvm.args>
    <version.docker.plugin>0.44.0</version.docker.plugin>
    <version.formatter.plugin>2.23.0</version.formatter.plugin>
    <version.impsort-maven-plugin>1.9.0</version.impsort-maven-plugin>
    <!-- This version needs to match the version in src/main/docker/opensearch-custom.Dockerfile -->
    <version.opensearch>2.11</version.opensearch>
  </properties>
```

The command will just remove them...

Version:

```
$ quarkus -v
3.7.4
```

**Comment by yrodiere** [comment]
No idea. Everybody reports Hibernate ORM bugs to Quarkus all the time, so I decided to follow the trend and not ask myself where the problem is exactly :D

**Comment by gsmet** [comment]
I see https://github.com/openrewrite/rewrite/issues/1392 but it looks old and fixed.

Can you provide a project and commit pointer which would allow me to reproduce. Thanks.

**Comment by yrodiere** [comment]
Ok, I'm sorry. The problem was with `quarkus ext add`, not with `quarkus update`.

I did only sleep 4h last night, in my defense. Still, sorry for the noise.

Any idea where I should report problems for `quarkus ext add`?

**Comment by gsmet** [comment]
Unfortunately quarkus ext add is rewriting the whole BOM. It is even changing the formatting and IMO shouldn't be used.

The problem should be reported in the Quarkus project.

**Comment by yrodiere** [comment]
Filed as https://github.com/quarkusio/quarkus/issues/39048
