### ISSUE TITLE
Enable ecosystem-ci for the quarkus-updates repo

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus-updates#23]
### Description

- Add ecosystem CI
- Add one test that generate 2.X app then migrate it and check the result.

**Comment by gsmet** [comment]
FWIW, these projects are very good candidates for testing (at least as a start):
- https://github.com/quarkiverse/quarkus-github-app/
- https://github.com/quarkusio/quarkus-github-bot/

**Comment by ia3andy** [comment]
This is done, for now it udpate a code quarkus basic project
