### ISSUE TITLE
Migration recipe does not contain the `org.hibernate.orm` groupId change

### ISSUE THREAD

**Issue by radtriste** [quarkusio/quarkus-updates#25]
Seems it is still using `org.hibernate` groupId change: https://github.com/quarkusio/quarkus-updates/blob/main/recipes/src/main/resources/quarkus-updates/core/3alpha.yaml#L924
Is that expected behavior ?

I am trying to migrate the Drools to Q3 CR1 and noticed the `hibernate-core` has changed in https://central.sonatype.com/artifact/io.quarkus/quarkus-bom/3.0.0.CR1

**Comment by radtriste** [comment]
@smet @aloubyansky

**Comment by gsmet** [comment]
You're right, this is incorrect and should be adjusted. I will go do that.

**Comment by gsmet** [comment]
This has been fixed today and will be released soon.

**Comment by radtriste** [comment]
Thank you
Gonna update our internal recipe then :)
