### ISSUE TITLE
Camel-quarkus: Recipe for upgrade java (to 17) is missing

### ISSUE THREAD

**Issue by JiriOndrusek** [quarkusio/quarkus-updates#50]
During the final refactor from https://github.com/quarkusio/quarkus-updates/pull/46, the recipe for java migration from 11 to 17 was removed.

Should be added together with the corresponding test.

**Comment by JiriOndrusek** [comment]
Please assign to me. I don't have the permission to do that.

**Comment by ia3andy** [comment]
This should be automatic @JiriOndrusek it's done by the Quarkus tooling already
